import {writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {renderWheel,defaultOptions} from '../outputs/dama-del-tiempo/web/wheel.js';
import {calculateAspects} from '../outputs/dama-del-tiempo/web/aspects.js';
import {referenceRows,rulerships,triplicities,terms,faces} from '../outputs/dama-del-tiempo/web/dignities.js';
const response=await fetch('http://127.0.0.1:8766/api/chart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:'2000-01-01',time:'12:00:00',latitude:51.4779,longitude:0,timezone:'Etc/UTC'})});
if(!response.ok)throw Error(await response.text());const data=await response.json();
const svg=renderWheel(data.results,defaultOptions,calculateAspects(data.results.bodies),'Greenwich · 1/1/2000 12:00 UTC');
writeFileSync('outputs/rueda-terminos-egipcios.svg',svg);
const require=createRequire(import.meta.url),{Resvg}=require('./svg-render/node_modules/@resvg/resvg-js');
writeFileSync('outputs/rueda-terminos-egipcios.png',new Resvg(svg,{fitTo:{mode:'width',value:3300}}).render().asPng());
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const span=s=>`${s.ruler} [${s.start}°, ${s.end}°)`;
const headers=['Signo','Domicilio','Detrimento','Exaltación','Caída','Triplicidad diurna','Nocturna','Participante','Términos egipcios','Faces'];
const rows=referenceRows().map(r=>[r.sign,r.domicile,r.detriment,r.exaltation?`${r.exaltation.planet} (${r.exaltation.degree}°)`:'—',r.fall?`${r.fall.planet} (${r.fall.degree}°)`:'—',r.triplicity.day,r.triplicity.night,r.triplicity.participant,r.terms.map(span).join('; '),r.faces.map(span).join('; ')]);
const table=`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const sources=[rulerships,triplicities,terms,faces].map(d=>`<li>${esc(d.system)}: <a href="${esc(d.reference)}">${esc(d.source)}</a> · versión ${d.version}</li>`).join('');
writeFileSync('outputs/tabla-completa-dignidades.html',`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dama del Tiempo · Tabla tradicional completa</title><style>body{font:16px/1.6 system-ui;background:#fffaf0;color:#16212f;margin:24px}h1,h2{font-family:Georgia}table{border-collapse:collapse;min-width:1600px}td,th{padding:12px;border:1px solid #dfd7d5;vertical-align:top;text-align:left}th{background:#f1e9e6}.scroll{overflow:auto}svg{width:100%;height:auto;max-width:1100px}li{margin:12px 0}</style><h1>Dignidades tradicionales — términos egipcios</h1><p>Triplicidades de Doroteo. Datos generados directamente desde los archivos que utiliza la aplicación.</p><h2>Tabla tradicional completa</h2><p>Intervalos [inicio, fin): comienzo inclusivo y final exclusivo. Los grados de exaltación y caída son referencias; la dignidad o debilidad corresponde al signo completo. Desplazá la tabla horizontalmente para ver todas sus columnas.</p><div class="scroll">${table}</div><h2>Fuentes</h2><ul>${sources}</ul><p>Triplicidad activa: regente principal por secta; participante informado por separado. Secta: altura geométrica del centro solar ≥0° diurna, &lt;0° nocturna. Sin puntos automáticos para el participante.</p><h2>Carta de ejemplo con términos</h2><p>Greenwich, 1 de enero de 2000, 12:00 UTC. Alcabitius. Carta ${data.sect.name}; altura solar ${data.sect.solar_altitude.toFixed(6)}°. Orbes planetarios medievales por semisuma.</p>${svg}</html>`);
writeFileSync('work/dignities-sample.json',JSON.stringify(data));
