const {chromium}=require('C:/Users/Users/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {resolve}=require('node:path');
const {pathToFileURL}=require('node:url');
const {writeFileSync}=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 await page.goto(pathToFileURL(resolve('outputs/catalogo-lotes-revision/catalogo.html')).href);
 assert.equal(await page.locator('#rows tr').count(),335);
 assert.equal(await page.locator('#seven tr').count(),7);
 await page.locator('#review').selectOption('dubious');assert.equal(await page.locator('#rows tr').count(),31);
 await page.locator('#review').selectOption('multipleSources');assert.equal(await page.locator('#rows tr').count(),14);
 await page.locator('#review').selectOption('unsupportedOperand');assert.equal(await page.locator('#rows tr').count(),17);
 await page.locator('#review').selectOption('specialCondition');assert.equal(await page.locator('#rows tr').count(),45);
 await page.locator('#review').selectOption('unresolvedSource');assert.equal(await page.locator('#rows tr').count(),9);
 await page.locator('#reset').click();
 await page.locator('#search').fill('Fortuna');assert.equal(await page.locator('#rows tr').count(),1);
 await page.locator('#rows button').click();assert(await page.locator('#detail').isVisible());assert((await page.locator('#detailbody').innerText()).includes('Ascendente + Luna − Sol'));await page.locator('#close').click();
 await page.locator('#reset').click();await page.locator('#primary').selectOption('PA');assert.equal(await page.locator('#rows tr').count(),5);
 await page.locator('#reset').click();await page.locator('#category').selectOption('Weather');assert((await page.locator('#rows tr').count())>0);
 await page.locator('#reset').click();await page.locator('#secondary').selectOption('HT');assert.equal(await page.locator('#rows tr').count(),4);
 await page.locator('#reset').click();await page.locator('#search').fill('Daimon');assert.equal(await page.locator('#rows tr').count(),1);
 await page.locator('#reset').click();await page.screenshot({path:'outputs/catalogo-lotes-revision/vista-catalogo.png'});
 await page.setViewportSize({width:390,height:844});assert(await page.locator('#search').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.screenshot({path:'work/lots/catalogo-mobile.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 const report='Comprobación navegador: 335 filas; siete iniciales; filtros Dub., Mult., operandos, condiciones, fuentes, categorías, nombres y alternativos; detalle; ancho móvil sin desborde del documento. Sin errores JavaScript ni solicitudes de red. OK.\n';
 writeFileSync('outputs/catalogo-lotes-revision/resultado-navegador.txt',report);console.log(report);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
